from app.api.routes import (
    admin_brands,
    admin_categories,
    admin_orders,
    admin_products,
    admin_skin_quiz_leads,
    auth,
    blog,
    brands,
    cart,
    categories,
    checkout,
    orders,
    payments,
    products,
    skin_quiz,
)

__all__ = [
    "admin_brands",
    "admin_categories",
    "admin_orders",
    "admin_products",
    "admin_skin_quiz_leads",
    "auth",
    "blog",
    "brands",
    "cart",
    "categories",
    "checkout",
    "orders",
    "payments",
    "products",
    "skin_quiz",
]
